import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Carousel from "../components/Carousel";
import Modal from "../components/Modal";

const Home: NextPage = () => {

  const [open, setOpen] = useState(false)

  return (
    <div className="bg-gradient-to-b from-indigo-900  to-black">
      <Head>
        <title>Next eSports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container h-full w-full max-w-full">
        <section>
          <div className="flex flex-wrap justify-center items-center pt-12">
            <div className="text-left md:w-6/12">
              <h1 className="text-6xl text-white font-bold line">
                NLW eSports
              </h1>
              <h2 className="text-4xl text-white font-normal mt-2">
                Next Level Week eSports
              </h2>
            </div>
            <div className="md:w-6/12 justify-center text-center">
              <Image src="/logo.png" width={350} height="300"></Image>
            </div>
          </div>
        </section>
        <section className="mt-8">
          <h1 className="text-6xl text-white font-bold line w-full text-center mb-8">
            Seu{" "}
            <b className="font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-[#6EE7B7] via-[#3B82F6] to-[#9333EA]">
              duo
            </b>{" "}
            está aqui.
          </h1>
          <Carousel></Carousel>
        </section>

        <section className="mt-8 pb-8">
          <div className="w-full rounded-xl bg-gradient-to-r pt-1 from-[#6EE7B7] via-[#3B82F6] to-[#9333EA]">
            <div className="flex flex-wrap items-center h-full bg-gray-900 text-white rounded-lg p-6">
              <div className="relative md:w-6/12 sm:w-full">
                <h2 className="font-semibold text-3xl mb-2">Não encontrou seu duo?</h2>
                <h5 className="font-normal text-1xl text-gray-500">Publique um anúncio para encontrar novos players!</h5>
              </div>
              <div className="flex md:w-6/12 md:justify-end w-full mt-2 md:mt-0">
                <button
                  onClick={() => setOpen(true)} 
                  className="bg-purple-600 flex items-center rounded-md p-4 text-xl font-medium md:w-56 sm:w-full justify-center"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6 mr-2">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>

                  Publicar anúncio
                </button>
              </div>
            </div>
          </div>
        </section>
        <Modal setOpen={setOpen} open={open}/>
      </main>
    </div>
  );
};

export default Home;
